import React, { Component } from 'react';
import { withRouter } from '../code/withRouter.js';

import Navigator from '../code/Navigator.js';
import LabName from '../code/LabName.js';
import NormalA from '../code/NormalA.js';
import * as d3time from 'd3-time-format'
import { isMobile } from 'react-device-detect';
import { _newspath } from '../code/helper.js'
import { Col, Card } from 'react-bootstrap';
import { PiCaretDoubleDownLight } from "react-icons/pi";
// import axios from 'axios';

const tParser = d3time.timeParse("%Y-%m-%d")
const oFormat = d3time.timeFormat("%Y %B")

class Home extends Component {




    constructor(props) {
        super(props);
    }


    componentDidMount() {
        // this.createVis()
        document.title = "FIGX | Home"
        
        fetch(_newspath)
            .then(response => response.json())
            .then(data => {
                data.sort((a, b) => {
                    a.timeFormatted = tParser(a.time)
                    b.timeFormatted = tParser(b.time)
                    return b.timeFormatted - a.timeFormatted
                })
                this.setState({ 'newsdata': data })
            }).catch(error => {
                console.log(error)
            })

        
    }

    componentDidUpdate() {
        // this.createVis();
    }


    render() {
        return (
            <div className='page-content'>
                <div className='top-header border-bottom' style={{ 'marginBottom': 0 }}>
                    <div className="container">
                        <Navigator activeItem='home-nav' />
                    </div>
                </div>

                <div className='welcome-block-outside border-bottom'>

                    <div className='welcome-block-inside'>
                        <div className="container">
                            <div >

                                <div className="row">

                                    <div class="bounce"><PiCaretDoubleDownLight /></div>



                                    <div className='row'>
                                        <div className='col-lg-3 mobile-only' style={{ 'textAlign': 'center' }}>
                                            <img src='figx-logo-full.svg' id="welcome-logo-left" ></img>

                                        </div>

                                        <div className='col-lg-8'>
                                            {/* <img src='figx-logo-2.png' id="welcome-logo-left" ></img> <br/> */}
                                            <p className='welcome-text'>Welcome to the FIGX Lab       </p>

                                            Our lab locates within the <NormalA
                                                href="https://www.cs.umd.edu/" text="Department of Computer
                                        Science"/> at the <NormalA href="https://umd.edu/" text="University of
                                            Maryland, College Park" />, and specializes in Human-Computer Interaction, Information Visualization, and Visual Computing. We create visual representations and interfaces designed to enhance understanding, interaction, and development of computational models, including probabilistic forecasts, machine learning, and foundational models.

                                            <br /> <br />
                                            <p className='small-note desktop-only'>The background image was generated by midjourney.</p>

                                        </div>
                                        <div className='col-lg-2 desktop-only' style={{ 'textAlign': 'center' }}>

                                            <img src='figx-logo-full.svg' id="welcome-logo-right" ></img>


                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>    </div>
                <div className="container">
                    <div className="padding-top"></div>
                    <div className="padding-top"></div>



                    <div className="row">
                        {/* <div> */}
                        <h2>About FIGX</h2>
                        <div id='topic-frontpage' className='col-lg-9' style={{ 'paddingTop': '10px' }}>
                            FIGX is an acronym for <b className='verybold'>Future Intelligent Graphical eXperience</b>. It can be thought of as <b className='verybold'>Fig. X</b>, the graphic representation that springs to mind when crafting an article. We chose this name to reflect our lab's commitment to pushing the boundaries of innovation and exploration in graphical experiences.

                        </div>   <div className="padding-top">   </div>

                        <h2>Lab news</h2>
                        <div id='news-containter' style={{ 'paddingTop': '10px' }}>

                            {this.state && this.state.newsdata && this.state.newsdata.map(d => {
                                return (
                                    <div className='row newsitem' >
                                        <div className='col-2 newsdate'>{oFormat(d.timeFormatted)}</div><div className='col-10 newscontent' dangerouslySetInnerHTML={{ __html: d.htmlContent }} />

                                    </div>
                                )
                            })
                            }
                        </div>
                    </div>

                    <div className="padding-top"></div>
                    <div className="row">


                    </div>


                </div>
                <br /><br /><br />

            </div >
        )
    }

}


export default withRouter(Home);